<?php

namespace Vecinos\ReservaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservaRepository extends EntityRepository
{
}