<?php

namespace Vecinos\UsuarioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
    
     /**
     * Encuentra todas las reservas del usuario indicado
     *
     * @param string $usuario El id del usuario
     */
    public function findTodasLasReservas($usuario)
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('SELECT r FROM ReservaBundle:Reserva r JOIN r.espacio e WHERE r.usuario = :id ORDER BY r.fecha DESC');
        $consulta->setParameter('id', $usuario); 
        
        return $consulta->getResult();
    }
    

    public function findTodasLasIncidencias()
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('SELECT i,u FROM IncidenciaBundle:Incidencia i JOIN i.usuario u '); 
        //$consulta->setParameter('usuario', $usuario);
        
        //return $consulta->getSingleResult();
        return $consulta->getResult();
    }
        
       // $consulta = $em->createQuery('SELECT o, c, t FROM OfertaBundle:Oferta o JOIN o.ciudad c JOIN o.tienda t WHERE o.revisada = true AND o.fecha_publicacion < :fecha AND c.slug = :ciudad ORDER BY o.fecha_publicacion DESC');
        
        
        
    
    
    public function queryTodasLasJuntas($usuario)
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('SELECT j FROM JuntaBundle:Junta j INNER JOIN j.usuarios u
                                                                              WHERE u.id = :id
                                                                              ORDER BY j.fecha DESC');
        $consulta->setParameter('id', $usuario); 
        
        return $consulta;
    }
    
     /**
     * Encuentra todas las juntas del usuario indicado
     *
     * @param string $usuario El id del usuario
     */
    public function findTodasLasJuntas($usuario)
    {
        
        return $this->queryTodasLasJuntas($usuario)->getResult();
        
    }
    
    /**
     * Encuentra todas los usuarios
     */
    public function findTodosLosUsuarios()
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('SELECT u FROM UsuarioBundle:Usuario u');
        
        return $consulta->getResult();
    }
}
