<?php

namespace Vecinos\UsuarioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
    
     /**
     * Encuentra todas las reservas del usuario indicado
     *
     * @param string $usuario El id del usuario
     */
    public function findTodasLasReservas($usuario)
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('SELECT r FROM ReservaBundle:Reserva r JOIN r.espacio e WHERE r.usuario = :id ORDER BY r.fecha DESC');
        $consulta->setParameter('id', $usuario); 
        
        return $consulta->getResult();
    }
    
    public function queryTodasLasIncidencias()
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('SELECT i FROM IncidenciaBundle:Incidencia i
                                                                              ORDER BY i.fecha DESC');
        
        return $consulta;
    }
    

    public function findTodasLasIncidencias()
    {
          return $this->queryTodasLasIncidencias()->getResult();
    }
    
    public function queryTodasLasJuntas($usuario)
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('SELECT j FROM JuntaBundle:Junta j INNER JOIN j.usuarios u
                                                                              WHERE u.id = :id
                                                                              ORDER BY j.fecha DESC');
        $consulta->setParameter('id', $usuario); 
        
        return $consulta;
    }
    
     /**
     * Encuentra todas las juntas del usuario indicado
     *
     * @param string $usuario El id del usuario
     */
    public function findTodasLasJuntas($usuario)
    {
        
        return $this->queryTodasLasJuntas($usuario)->getResult();
        
    }
    
    /**
     * Encuentra todas los usuarios
     */
    public function findTodosLosUsuarios()
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('SELECT u FROM UsuarioBundle:Usuario u');
        
        return $consulta->getResult();
    }
}
