<?php

namespace Vecinos\UsuarioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
    
     /**
     * Encuentra todas las reservas del usuario indicado
     *
     * @param string $usuario El id del usuario
     */
    public function findTodasLasReservas($usuario)
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('SELECT r FROM ReservaBundle:Reserva r JOIN r.espacio e WHERE r.usuario = :id ORDER BY r.fecha DESC');
        $consulta->setParameter('id', $usuario); 
        
        return $consulta->getResult();
    }
}