<?php

namespace Vecinos\JuntaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JuntaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JuntaRepository extends EntityRepository
{
}