<?php

namespace Vecinos\IncidenciaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IncidenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class IncidenciaRepository extends EntityRepository {

    public function getTags() {
        $blogTags = $this->createQueryBuilder('b')
                ->select('b.tags')
                ->getQuery()
                ->getResult();

        $tags = array();
        foreach ($blogTags as $blogTag) {
            $tags = array_merge(explode(",", $blogTag['tags']), $tags);
        }

        foreach ($tags as &$tag) {
            $tag = trim($tag);
        }

        return $tags;
    }

    public function getTagWeights($tags) {
        $tagWeights = array();
        if (empty($tags))
            return $tagWeights;

        foreach ($tags as $tag) {
            $tagWeights[$tag] = (isset($tagWeights[$tag])) ? $tagWeights[$tag] + 1 : 1;
        }
        // Shuffle the tags
        uksort($tagWeights, function() {
                    return rand() > rand();
                });

        $max = max($tagWeights);

        // Max of 5 weights
        $multiplier = ($max > 5) ? 5 / $max : 1;
        foreach ($tagWeights as &$tag) {
            $tag = ceil($tag * $multiplier);
        }

        return $tagWeights;
    }
    
    public function findIncidenciasByTag($tag)
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('SELECT i FROM IncideniaBundle:Incidencia i INNER JOIN i.tags t
                                                                              WHERE t = :tag');
        $consulta->setParameter('tag', $tag); 
        
        return $consulta->getResult();

    }

}