<?php

namespace Vecinos\IncidenciaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IncidenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncidenciaRepository extends EntityRepository
{
    
    public function findTodasLasIncidencias($id)
  {
      $em = $this->getEntityManager();
      $consulta = $em->createQuery('SELECT u FROM IncidenciaBundle:Incidencia u');
      $consulta->setParameter('id', $id);
      
                
      return $consulta->getResult();

  }
}