<?php

namespace Vecinos\EspacioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EspacioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspacioRepository extends EntityRepository
{
}